#ifndef NET_SOCKET_IOS_CRONET_BUILDFLAGS_H_
#define NET_SOCKET_IOS_CRONET_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CRONET_BUILD() (0)

#endif  // NET_SOCKET_IOS_CRONET_BUILDFLAGS_H_
