#ifndef BASE_SYNCHRONIZATION_BUILDFLAGS_H_
#define BASE_SYNCHRONIZATION_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_MUTEX_PRIORITY_INHERITANCE() (0)

#endif  // BASE_SYNCHRONIZATION_BUILDFLAGS_H_
